server:
  port: 8091

management:
  server:
    port: 9091
    # address: 127.0.0.1

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: redis@123456#
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  path: d:/web_logs/blue_cat
  file: d:/web_logs/blue_cat/auth.log
  pattern:
    console: "%d - %msg%n"

datasource:
  master:
    url: jdbc:mysql://127.0.0.1:3306/auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: auth
    password: auth#2019
  slave:
    url: jdbc:mysql://127.0.0.1:3306/auth?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=true
    username: auth
    password: auth#2019

rest:
  template:
    read-timeout: 10000
    connect-timeout: 20000
