info:
  app:
    name: auth-server
    version: 1.0.0

spring:
  messages:
    basename: BindingErrorMessages
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
    tomcat:
      max-wait: 50000
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        default_catalog: auth
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

datasource:
  validation-query: SELECT 1
  driver-class-name: org.mariadb.jdbc.Driver
#  driver-class-name: com.mysql.cj.jdbc.Driver
  max-active: 20
  min-idle: 1
  initial-size: 10

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000

logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"

security:
  #单位小时
  expireTime: 2
  time-out:
    #单位秒
    sign-up: 3600
    #单位小时
    user: 24
    #单位分钟
    idempotent: 10
  tokenSalt: jarod.jin
  tokenPrefix: Bearer
  permitAll:
    - /monitor/*
    - /access/**
    - /token
  route:
    authentication:
      path: /login
      refresh: /refresh
      register: /register

