server:
  port: 8082
  servlet:
    context-path: /auth/api

management:
  server:
    port: 8092
    # address: 127.0.0.1

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: BLUE_CAT_GROUP
        namespace: 16f4847c-1396-47f2-b9ff-efc17818287c
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis@123456#
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      #同127.0.0.1
      host: localhost
      port: 27017
      #指定操作的数据库
      database: admin
      username: root
      password: root@1234

logging:
  file:
    name: d:/web_logs/blue_cat/auth.log
    path: d:/web_logs/blue_cat

datasource:
  master:
    url: jdbc:mysql://127.0.0.1:3306/auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: auth
    password: auth#2019
  slave:
    url: jdbc:mysql://127.0.0.1:3305/auth?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=true
    username: auth
    password: auth#2019

rest:
  template:
    read-timeout: 10000
    connect-timeout: 20000
