info:
  app:
    name: gateway-server
    version: 1.0.0

spring:
  messages:
    basename: BindingErrorMessages
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
    tomcat:
      max-wait: 50000
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: estimate_service
          uri: lb://estimate
          predicates:
            - Path=/api/estimate/**
        - id: general_service
          uri: lb://general
          predicates:
            - Path=/api/general/**
        - id: analyst_service
          uri: lb://analyst
          predicates:
            - Path=/api/analyst/**


management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000

security:
  expirationTime: 28800000
  tokenSalt: jarod.jin
  tokenPrefix: Bearer
  loginUrl: /api/auth/login
  permitAllUrl:
    - /monitor/*
    - /api/auth/register

feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true

