server:
  port: 8080

management:
  server:
    port: 8090
  health:
    elasticsearch:
      enabled: false

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: BLUE_CAT_GROUP
        namespace: BLUE_CAT_GROUP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis@123456#
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  file:
    name: d:/web_logs/blue_cat/gateway.log
    path: d:/web_logs/blue_cat

useLocalCache: lisi