# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@1234

  mongo-express:
    image: mongo-express
    container_name: my-mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root@1234